# [START cloudbuild_gradle]
steps:
  - name: gradle:8-jdk17
    entrypoint: gradle
    args: ["test"]
  - name: gradle:8-jdk17
    entrypoint: gradle
    args: ["assemble"]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/foobar:$COMMIT_SHA', '-t', 'us.gcr.io/$PROJECT_ID/foobar:latest', '.' ]
images:
- 'us.gcr.io/$PROJECT_ID/foobar:$COMMIT_SHA'
- 'us.gcr.io/$PROJECT_ID/foobar:latest'
timeout: 3600s
# [END cloudbuild_gradle]