steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA', '.' , '-f', 'Dockerfile']
    timeout: 600s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA']
  # Deploy an image from Container Registry to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
      - 'run'
      - 'deploy'
      - '$_BINARY_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--region'
      - '$_REGION'
      - '--allow-unauthenticated'
timeout: 5000s
images:
- 'gcr.io/$PROJECT_ID/$_BINARY_NAME:$COMMIT_SHA'
