# [START cloudbuild_gradle]
steps:
  - name: gradle:8-jdk17
    entrypoint: gradle
    args: ["test"]
  - name: gradle:8-jdk17
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "eu.gcr.io/$PROJECT_ID/integrax-backend-service", "--build-arg=JAR_FILE=build/libs/integrax-backend-service-1.0.0.jar", "."]
images: ["eu.gcr.io/$PROJECT_ID/$_REPO_NAME/integrax-backend-service"]
# [END cloudbuild_gradle]