steps:
  - name: 'gradle:8.5-jdk17'
    entrypoint: 'gradle'
    args: ['build', '-x', 'test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/companieshouse', '.']
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/companieshouse"]
  - name: "gcr.io/cloud-builders/docker"
    env:
      - 'DOCKER_USER=eu.gcr.io/$PROJECT_ID'
      - 'DOCKER_IMAGE=companieshouse'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'companieshouse',
      '--image',
      'eu.gcr.io/$PROJECT_ID/companieshouse',
      '--region',
      'europe-west1',
      '--allow-unauthenticated',
      '--platform',
      'managed',
    ]